- name: Update apt cache and install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx
  ansible.builtin.copy:
    src: files/nginx_reverse_proxy.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
  notify: Restart Configure Nginx

- name: Configure Symlink
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart Configure Nginx